development: &development
  :url: redis://localhost:6379
  :host: localhost
  :port: 6379
  :timeout: 1
  :inline: true
test: *development
production: &production
  :url:     redis://default:aXH1XclkbtHfxZr4dz9yUg7Y7RczMOrX@redis-12654.c244.us-east-1-2.ec2.cloud.redislabs.com:12654
  :host: redis-12654.c244.us-east-1-2.ec2.cloud.redislabs
  :port: 12654
  :password: aXH1XclkbtHfxZr4dz9yUg7Y7RczMOrX
  :inline: true
  :timeout: 1
